/**
 * The canonical privacy policy, as structured data.
 *
 * Content is derived from the verified compliance research for this app
 * (minimal-risk AI system; Art. 50 transparency binds; lawful bases split
 * between contract and legitimate interest). Kept as data rather than a
 * markdown file so it renders with no parser dependency and so the tests can
 * assert on individual disclosures — in particular the Brave query-text
 * disclosure, which Brave's Search API terms §3b make contractually
 * mandatory on top of the GDPR duty.
 */

export const LAST_UPDATED = "2026-08-25";

export const MINIMUM_AGE = 16;

/** Stated retention period for pipeline telemetry, per GDPR Art. 5(1)(e). */
export const RETENTION_DAYS = 90;

export type PolicySection = {
  heading: string;
  paragraphs: string[];
};

export const PRIVACY_POLICY: PolicySection[] = [
  {
    heading: "Who is responsible",
    paragraphs: [
      "Bandsearch is an open-source music discovery app. When you run it on your own machine with your own API keys, you are in control of your own data and Bandsearch is only the software you use to process it.",
      "When you use a shared, hosted deployment with an account, whoever operates that deployment is the data controller and is the right contact for any question about your data.",
    ],
  },
  {
    heading: "What is stored, and where",
    paragraphs: [
      "Your account: email address, display name, and a bcrypt hash of your password and recovery code. Passwords and recovery codes themselves are never stored and cannot be recovered from the hashes.",
      "Your taste profile: the artists you save, your 1-5 ratings, categories, and any notes you write.",
      "Your conversations: the chat sessions and messages you exchange with the assistant.",
      "Pipeline telemetry: anonymous records of how a search performed, used to measure and improve recommendation quality. These carry no account identifier and cannot be traced back to you.",
      "On the desktop app, your API keys and login token are stored locally in your operating system's config directory, never on a server.",
    ],
  },
  {
    heading: "Why we are allowed to process it",
    paragraphs: [
      "Your taste profile and conversations are processed to deliver the personalised recommendations you asked for. That is the service itself, so the legal basis is performance of a contract (GDPR Art. 6(1)(b)).",
      "Pipeline telemetry is processed on the basis of legitimate interest (Art. 6(1)(f)) — improving recommendation quality. You have the right to object to this under Art. 21.",
      "We do not ask for or infer special category data. Music taste can occasionally correlate with beliefs or background, but Bandsearch never derives such inferences, and building any feature that did would be out of scope by design.",
    ],
  },
  {
    heading: "Profiling and how recommendations are made",
    paragraphs: [
      "Bandsearch builds a taste profile from the artists you save and how you rate them, and uses it to shape future recommendations. This is profiling in the sense of GDPR Art. 4(4).",
      "The main parameters are: the artists you saved, your ratings, the genres and tags attached to those artists, and the obscurity level you selected. There is no automated decision that produces a legal or similarly significant effect for you — the output is a list of bands to listen to.",
      "Recommendations and the explanations beside them are generated by an AI model, not written or curated by a person. Every suggested artist is checked against a real MusicBrainz record before it reaches you.",
    ],
  },
  {
    heading: "Who else receives your data",
    paragraphs: [
      "Google (Gemini API): your search text and conversation context are sent to Google's Gemini API to plan searches and write recommendations. Google LLC is certified under the EU-US Data Privacy Framework, with Standard Contractual Clauses as a fallback safeguard.",
      "Brave Search API: your search queries are sent to Brave to find candidate artists. Brave retains query records for up to 90 days for billing and troubleshooting purposes.",
      "MusicBrainz: artist names only — no account identifier and nothing about you — are sent to verify that a suggested artist exists.",
      "Last.fm (optional): if enabled, artist names are sent to fetch images and popularity data. This integration is off unless configured.",
      "Turso: when a deployment is configured to use Turso, your account data and taste profile are stored in that database rather than locally.",
    ],
  },
  {
    heading: "How long it is kept",
    paragraphs: [
      `Pipeline telemetry is deleted after ${RETENTION_DAYS} days.`,
      "Your account, taste profile and conversations are kept for as long as your account exists. When you delete your account, all of it is deleted with it, immediately and permanently.",
    ],
  },
  {
    heading: "Your rights",
    paragraphs: [
      "You can download everything held about you at any time from Settings → Privacy & data (\"Export my data\"). This covers your right of access (Art. 15) and portability (Art. 20).",
      "You can delete your account and all associated data from the same place. Deletion is immediate and cannot be undone, and there is no backup copy kept afterwards (Art. 17).",
      "You can correct anything wrong by editing your saved artists directly (Art. 16), and you can object to telemetry processing (Art. 21) by contacting whoever operates your deployment.",
      "If you believe your data is being handled unlawfully, you have the right to complain to your national data protection authority.",
    ],
  },
  {
    heading: "Age",
    paragraphs: [
      `Bandsearch is not intended for children. You should be at least ${MINIMUM_AGE} years old to create an account, or the minimum age set by the law where you live if it is lower.`,
    ],
  },
];
